import Foundation

public enum ActionID: String, CaseIterable, Codable, Hashable, Sendable {
    case documentOpen = "document.open"
    case documentClose = "document.close"
    case documentPrint = "document.print"
    case documentCopyPath = "document.copyPath"
    case documentRevealInFinder = "document.revealInFinder"
    case appQuit = "app.quit"
    case appNew = "app.new"
    case paletteOpen = "palette.open"

    case helpShow = "help.show"
    case tabNext = "tab.next"
    case tabPrevious = "tab.previous"
    case tabSelect1 = "tab.select.1"
    case tabSelect2 = "tab.select.2"
    case tabSelect3 = "tab.select.3"
    case tabSelect4 = "tab.select.4"
    case tabSelect5 = "tab.select.5"
    case tabSelect6 = "tab.select.6"
    case tabSelect7 = "tab.select.7"
    case tabSelect8 = "tab.select.8"
    case tabSelect9 = "tab.select.9"

    case scrollLeft = "scroll.left"
    case scrollDown = "scroll.down"
    case scrollUp = "scroll.up"
    case scrollRight = "scroll.right"
    case scrollLargeDown = "scroll.largeDown"
    case scrollLargeUp = "scroll.largeUp"

    case tocToggle = "toc.toggle"
    case tocScrollDown = "toc.scrollDown"
    case tocScrollUp = "toc.scrollUp"
    case pageNext = "page.next"
    case pagePrevious = "page.previous"
    case pageFirst = "page.first"
    case pageLast = "page.last"
    case pagePrompt = "page.prompt"
    case historyBack = "history.back"
    case historyForward = "history.forward"

    case promptCommit = "prompt.commit"
    case promptCancel = "prompt.cancel"

    case searchPrompt = "search.prompt"
    case searchNext = "search.next"
    case searchPrevious = "search.previous"
    case searchCancel = "search.cancel"

    case viewZoomIn = "view.zoomIn"
    case viewZoomOut = "view.zoomOut"
    case viewZoomReset = "view.zoomReset"
    case viewFitWidth = "view.fitWidth"
    case viewFitPage = "view.fitPage"
    case viewRotateLeft = "view.rotateLeft"
    case viewRotateRight = "view.rotateRight"
    case linkHint = "link.hint"

    case configReload = "config.reload"
    case configWriteDefault = "config.writeDefault"
    case configResetDefault = "config.resetDefault"
    case themePicker = "theme.picker"
    case indicatorPicker = "indicator.picker"
    case updateShow = "update.show"
    case paneSplitRight = "pane.splitRight"
    case paneSplitDown = "pane.splitDown"
    case paneFocusLeft = "pane.focusLeft"
    case paneFocusDown = "pane.focusDown"
    case paneFocusUp = "pane.focusUp"
    case paneFocusRight = "pane.focusRight"
    case paneUnsplit = "pane.unsplit"
}
